site_name: Mariusz Skomra
nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Experience: experience.md
  - Skills: skills.md
  - Education: education.md
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
